---
- name: Clone the dotfiles repo
  git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "{{ home }}/.dotfiles"
    update: true
  register: dotfiles

- name: Backup the config folders
  copy:
    src: "{{ item }}"
    remote_src: yes
    dest: "{{ item }}.bak"
  with_items: "{{ backup_targets }}"
  ignore_errors: yes
  failed_when: false
  when: dotfiles.changed

- name: Remove old config files
  file:
    name: "{{ item }}"
    state: absent
  with_items: "{{ backup_targets }}"
  ignore_errors: yes
  failed_when: false
  when: dotfiles.changed

- name: Symlink dotfiles with stow
  shell:
    cmd: "{{ home }}/.dotfiles/deploy.sh"
    chdir: "{{ home }}/.dotfiles"
  when: dotfiles.changed

