---
- name: Install necessary packages
  pacman:
    name: "{{ mandatory_packages }}"
  become: true

- name: Install optional packages
  pacman:
    name: "{{ optional_packages }}"
  become: true

- name: Install necessary pip packages
  pip:
    name: "{{ mandatory_pip_libraries }}"
    extra_args: --user

- name: Install optional pip packages
  pip:
    name: "{{ optional_pip_libraries }}"
    extra_args: --user

- name: Install required npm packages
  npm:
    name: "{{ item }}"
    global: true
  with_items: "{{ mandatory_npm_packages }}"
  become: true

- name: Install optional npm packages
  npm:
    name: "{{ item.name }}"
    global: true
  with_items:
    - name: "{{ optional_npm_packages }}"
  become: true

- name: Vim
  block:
    - name: make sure vim has autoload dir
      file:
        path: "{{ home }}/.vim/autoload"
        state: directory
    - name: install vimplug for vim
      get_url:
        url: >
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ home }}/.vim/autoload/plug.vim"
          # TODO also install the plugins while we're at it

- name: Neovim
  block:
    - name: Install latest neovim
      get_url:
        url: >
          https://github.com/neovim/neovim/releases/download/v0.6.1/nvim.appimage
        dest: /usr/local/bin/nvim
        mode: '755'
      become: true

    - name: Make sure neovim has autoload dir
      file:
        path: "{{ home }}/.local/share/nvim/site/autoload"
        state: directory

    - name: Install vimplug for neovim
      get_url:
        url: >
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ home }}/.local/share/nvim/site/autoload/plug.vim"

    # TODO: decide around March if this needs to be removed for real
    # - name: Install python2 env for neovim
    #   pip:
    #     name:
    #       - pynvim
    #       - neovim
    #     virtualenv: "{{ home }}/.pynvim"
    #     virtualenv_python: python2

    - name: Install python3 env for neovim
      pip:
        name:
          - pynvim
          - neovim
        virtualenv: "{{ home }}/.pynvim3"

# Check when there is a pacman package for lunarvim so we can get rid of this
- name: Lunarvim
  block:
  - name: Check if lunarvim is installed
    shell:
      cmd: "which lvim"
    register: lvim_installed
    failed_when: false

  - name: Install lunarvim
    shell:
      cmd: "LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh) --no-install-dependencies"
    when: lvim_installed.rc == 1
